name = "archi-law-cl-01"
compatibility_date = "2025-01-01"

# Pages Functions에서는 [[d1_databases]] 바인딩을 사용
[[d1_databases]]
binding = "DB"
database_name = "archi_law_db"
database_id = "2e1e9a33-8bf5-4824-aa73-89e1eb13cc75"
